/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hima.sejie.dao;

import java.util.List;

public interface IDao {   
	/**
	 * Inserts a new row in the user table.
	 */
	public Object insert(Object obj) throws Exception;

	/**
	 * Updates a single row in the user table.
	 */
	public Object update(Object obj) throws Exception;

	/**
	 * Deletes a single row in the user table.
	 */
	public Object delete(Integer id) throws Exception;

	/**
	 * Returns all rows from the user table that match the criteria 'id = :id'.
	 */
	public Object findByPrimaryKey(Integer id) throws Exception;

	/**
	 * Returns all rows from the user table that match the criteria ''.
	 */
	public List findAll() throws Exception;

	/**
	 * Returns all rows from the user table that match the criteria 'name =
	 * :name'. ͨ������ģ���ѯ
	 */
	public List findWhereNameEquals(String name) throws Exception;

	/**
	 * Returns all rows from the user table that match the specified arbitrary
	 * SQL statement
	 */
	public List findByDynamicSelect(String sql, Object[] sqlParams)
			throws Exception;

	public Object executeSQL(String sql, Object[] sqlParams) throws Exception;
}
